### ISSUE TITLE
Make react a peer dependency

### ISSUE THREAD

**Issue by PraveenPeri** [dgonz64/rhfa-material-ui#12]
"react" is currently under dev dependencies with version 16.x.x.x which would cause "Invalid hook call" exception in the downstream apps consuming this library if the app has a different react version(say 17.0.2) in it. 
So I propose to add react: "*" as peer dependency instead without even locking into a specific version.

**Comment by dgonz64** [comment]
Updated `react-hook-form-auto` to 1.2.11. It now allows both react 16 and 17. Can you check if it works for you, please?
