### ISSUE TITLE
AutoForm is not exported with forwardRef

### ISSUE THREAD

**Issue by PraveenPeri** [dgonz64/rhfa-material-ui#7]
The AutoForm component from this library is not exported with forwardRef. As a result, .current property on useRef in my own code always ends up null.<br />
`import { Autoform } from rhfa-material-ui`<br />
`let formRef;` <br />
`const handleSubmit = () => formRef.current.submit(); // throws error "cannot find submit() of property null"`<br />
`<Autoform ref={formRef} />`<br />
`<Button onClick={handleSubmit}>Ok</Button>`

**Comment by dgonz64** [comment]
Sorry about that. Fixed in `1.1.3` just released.

**Comment by PraveenPeri** [comment]
Thanks for fixing the issue
